# Generated by Django 5.1.7 on 2025-03-13 07:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wntd_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wntd',
            name='status',
            field=models.CharField(choices=[('Pass', 'Pass'), ('Under Testing', 'Under Testing'), ('Under Opti', 'Under Opti'), ('Under Assurance', 'Under Assurance'), ('Products', 'Products'), ('Fail', 'Fail')], default='HomeFast', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='wntdhistory',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
