# Generated by Django 5.1.7 on 2025-03-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('super-admin', 'Super Admin'), ('admin', 'Admin'), ('manager', 'Manager'), ('engineer', 'Engineer'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
