# Generated by Django 5.1.7 on 2025-03-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(choices=[('management', 'Management'), ('engineering', 'Engineering'), ('operations', 'Operations'), ('support', 'Support'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
