# Generated by Django 5.1.7 on 2025-03-14 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_grant_superadmin_to_specific_users'),
        ('authentication', '0003_userprofile_date_modified_userprofile_department'),
    ]

    operations = [
    ]
